# Generated by Django 4.1.3 on 2023-01-11 22:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('softdesk', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Users',
        ),
        migrations.RemoveField(
            model_name='comments',
            name='author',
        ),
        migrations.RemoveField(
            model_name='comments',
            name='issue',
        ),
        migrations.RemoveField(
            model_name='contributors',
            name='project',
        ),
        migrations.RemoveField(
            model_name='contributors',
            name='user',
        ),
        migrations.RemoveField(
            model_name='issues',
            name='assignee',
        ),
        migrations.RemoveField(
            model_name='issues',
            name='author',
        ),
        migrations.RemoveField(
            model_name='issues',
            name='desc',
        ),
        migrations.RemoveField(
            model_name='issues',
            name='project',
        ),
        migrations.RemoveField(
            model_name='projects',
            name='author',
        ),
        migrations.AddField(
            model_name='comments',
            name='author_user_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='comments',
            name='issue_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='softdesk.issues'),
        ),
        migrations.AddField(
            model_name='contributors',
            name='projet_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='softdesk.projects'),
        ),
        migrations.AddField(
            model_name='contributors',
            name='user_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='issues',
            name='assignee_user_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assignee_id', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='issues',
            name='author_user_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='author_id', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='issues',
            name='description',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='issues',
            name='project_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='softdesk.projects'),
        ),
        migrations.AddField(
            model_name='projects',
            name='author_user_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='comments',
            name='created_time',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='contributors',
            name='permission',
            field=models.CharField(choices=[('RESTRICTED', 'contributor'), ('ADMIN', 'author')], default='RESTRICTED', max_length=80),
        ),
        migrations.AlterField(
            model_name='contributors',
            name='role',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='issues',
            name='created_time',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='issues',
            name='priority',
            field=models.CharField(choices=[('HIGH', 'high'), ('MEDIUM', 'medium'), ('LOW', 'low')], max_length=255),
        ),
        migrations.AlterField(
            model_name='issues',
            name='status',
            field=models.CharField(choices=[('ONGOING', 'ongoing'), ('TO DO', 'to do'), ('DONE', 'done')], max_length=255),
        ),
        migrations.AlterField(
            model_name='issues',
            name='tag',
            field=models.CharField(choices=[('BUG', 'bug'), ('UPDATE', 'update'), ('TASK', 'task')], max_length=255),
        ),
        migrations.AlterField(
            model_name='issues',
            name='title',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='projects',
            name='title',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='projects',
            name='type',
            field=models.CharField(choices=[('BACK', 'back-end'), ('FRONT', 'front-end'), ('IOS', 'iOs'), ('ANDROID', 'android')], max_length=80),
        ),
    ]
