# Generated by Django 4.1.3 on 2023-01-04 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('softdesk', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Users',
        ),
        migrations.RemoveField(
            model_name='contributors',
            name='permission',
        ),
        migrations.AlterField(
            model_name='issues',
            name='status',
            field=models.CharField(blank=True, choices=[('ONGOING', 'ongoing'), ('TO DO', 'to do'), ('DONE', 'done')], max_length=16, null=True),
        ),
        migrations.AlterField(
            model_name='issues',
            name='tag',
            field=models.CharField(blank=True, choices=[('BUG', 'bug'), ('UPDATE', 'update'), ('TASK', 'task')], max_length=16, null=True),
        ),
        migrations.AlterField(
            model_name='projects',
            name='type',
            field=models.CharField(choices=[('BACK', 'back-end'), ('FRONT', 'front-end'), ('IOS', 'iOs'), ('ANDROID', 'android')], max_length=7),
        ),
    ]
