# Generated by Django 4.1.3 on 2023-01-11 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('softdesk', '0002_delete_users_remove_comments_author_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comments',
            name='description',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='contributors',
            name='role',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='issues',
            name='description',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='issues',
            name='status',
            field=models.CharField(blank=True, choices=[('ONGOING', 'ongoing'), ('TO DO', 'to do'), ('DONE', 'done')], max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='issues',
            name='title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='projects',
            name='description',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='projects',
            name='title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
