# Generated by Django 4.1.3 on 2023-01-13 03:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('softdesk', '0003_alter_comments_description_alter_contributors_role_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contributors',
            old_name='projet_id',
            new_name='project_id',
        ),
    ]
